from setuptools import setup, find_packages

setup(
    name="marketflow",
    version="0.1.0",
    packages=find_packages(exclude=["tests*"]),
    install_requires=[
        "pandas",
        "numpy",
        "requests",
        "python-dotenv",
        "absl-py==2.3.0",
        "annotated-types==0.7.0",
        "anyio==4.9.0",
        "astunparse==1.6.3",
        "beautifulsoup4==4.13.4",
        "blinker==1.9.0",
        "certifi==2025.1.31",
        "charset-normalizer==3.4.1",
        "chex==0.1.89",
        "click==8.1.8",
        "colorama==0.4.6",
        "contourpy==1.3.2",
        "cycler==0.12.1",
        "distro==1.9.0",
        "docx==0.2.4",
        "etils==1.12.2",
        "filelock==3.18.0",
        "Flask==3.0.3",
        "flatbuffers==25.2.10",
        "flax==0.10.6",
        # Add other dependencies here
    ],
    author="Your Name",
    author_email="joaoboscojbm@gmail.com",
    description="A modular, extensible Python framework for advanced Volume-Price Analysis (VPA) and Wyckoff Method analytics.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Martinolli/marketflow",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)