"""Build the offline evidence-package preparation candidate after blocked acquisition."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any, Mapping

from marketflow.historical_data.artifacts import semantic_digest
from marketflow.services import (
    marketflow_repository_integration_branch_retry_failure_source_authority_acquisition_execution_after_candidate_operator_review_failure_diagnosis_service
    as source,
)


ARTIFACT_KIND = "MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_V1"
SCHEMA_VERSION = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1"
CANDIDATE_STATUS = "MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_READY_FOR_OPERATOR_REVIEW"
CANDIDATE_SCOPE = "REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_ONLY_NOT_APPROVAL_NOT_EXECUTION_NOT_EVIDENCE_PACKAGE_CREATION_NOT_SOURCE_AUTHORITY_ACQUISITION_NOT_EVIDENCE_ACQUISITION_NOT_NO_CHANGE_DISPOSITION_NOT_REMEDIATION_NOT_RETRY_NOT_MAIN"
SOURCE_FAILURE_DIAGNOSIS_COMMIT = "e51b3f58215a3ecb25f863655c79490cbdd65342"
SOURCE_FAILURE_DIAGNOSIS_DIGEST = "4ecc51acb6b037757e6dfcb406af8afc45627bc0bc5487feea2af88b79fc232c"
SOURCE_FAILURE_CLASSIFICATION_DIGEST = "dfcc0f7438afd861300bac7bcde4b5449b3f1f969547f09469c378707c6e084a"
SOURCE_MISSING_EVIDENCE_PACKAGE_DIAGNOSIS_DIGEST = "918dba1b6c9a6e0d3d8bc2919525af046e2c8e460d13741284b2838d87df4b95"
SOURCE_COVERAGE_DIAGNOSIS_DIGEST = "233b3a47c56e8862df92d03f305d22be10ccec0dc6e2278f69260fe98e9373f4"
SOURCE_FAILURE_DIAGNOSIS_MANIFEST_DIGEST = "25c87db09e1464ad5466a2fc007d510df94ccae40b9da8eef44ee987698002a6"
PRIMARY_FAILURE_CLASS = "NO_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PROVIDED"
RECOMMENDED_PACKAGE = "PACKAGE_CREATE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_TEMPLATE_FROM_REVIEWED_ACQUISITION_SCOPE_ONLY"
PACKAGE_CREATE_SOURCE_OWNER_REQUEST_REQUIREMENTS_FOR_30_MISSING_AUTHORITY_ITEMS = "PACKAGE_CREATE_SOURCE_OWNER_REQUEST_REQUIREMENTS_FOR_30_MISSING_AUTHORITY_ITEMS"
PACKAGE_CREATE_LIMITED_ASSERTION_VALUE_SOURCE_EVIDENCE_TEMPLATE = "PACKAGE_CREATE_LIMITED_ASSERTION_VALUE_SOURCE_EVIDENCE_TEMPLATE"
PACKAGE_CREATE_LIMITED_DIGEST_SERIALIZATION_SOURCE_EVIDENCE_TEMPLATE = "PACKAGE_CREATE_LIMITED_DIGEST_SERIALIZATION_SOURCE_EVIDENCE_TEMPLATE"
PACKAGE_CREATE_LIMITED_FIXTURE_DETERMINISM_SOURCE_EVIDENCE_TEMPLATE = "PACKAGE_CREATE_LIMITED_FIXTURE_DETERMINISM_SOURCE_EVIDENCE_TEMPLATE"
PACKAGE_CREATE_LIMITED_SCHEMA_FIELD_CONTRACT_SOURCE_EVIDENCE_TEMPLATE = "PACKAGE_CREATE_LIMITED_SCHEMA_FIELD_CONTRACT_SOURCE_EVIDENCE_TEMPLATE"
PACKAGE_HOLD_PENDING_OPERATOR_SOURCE_AUTHORITY_EVIDENCE = "PACKAGE_HOLD_PENDING_OPERATOR_SOURCE_AUTHORITY_EVIDENCE"
PACKAGE_GENERATE_EVIDENCE_FROM_DIAGNOSTIC_OUTPUT = "PACKAGE_GENERATE_EVIDENCE_FROM_DIAGNOSTIC_OUTPUT"
PACKAGE_ACCEPT_APPROVAL_AS_OPERATOR_EVIDENCE_PACKAGE = "PACKAGE_ACCEPT_APPROVAL_AS_OPERATOR_EVIDENCE_PACKAGE"
PACKAGE_FABRICATE_OR_INFER_MISSING_SOURCE_AUTHORITY_EVIDENCE = "PACKAGE_FABRICATE_OR_INFER_MISSING_SOURCE_AUTHORITY_EVIDENCE"
PACKAGE_RETRY_SOURCE_AUTHORITY_ACQUISITION_WITHOUT_EVIDENCE_PACKAGE = "PACKAGE_RETRY_SOURCE_AUTHORITY_ACQUISITION_WITHOUT_EVIDENCE_PACKAGE"
PACKAGE_REMEDIATION_OR_RETRY_OR_MAIN_MERGE_FROM_MISSING_EVIDENCE_DIAGNOSIS = "PACKAGE_REMEDIATION_OR_RETRY_OR_MAIN_MERGE_FROM_MISSING_EVIDENCE_DIAGNOSIS"
RECOMMENDED_TASK = "MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_OPERATOR_REVIEW_AFTER_BLOCKED_ACQUISITION_EXECUTION_V1"
CANDIDATE_DIGEST_KEY = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_digest"
PACKAGE_OPTIONS_DIGEST_KEY = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_package_options_digest"
TEMPLATE_REQUIREMENTS_DIGEST_KEY = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_template_requirements_digest"
COVERAGE_DIGEST_KEY = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_missing_authority_coverage_digest"
MANIFEST_DIGEST_KEY = "marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_manifest_digest"
PASS, BLOCKER = "PASS", "BLOCKER"

ARTIFACT_KIND_MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_V1 = ARTIFACT_KIND
MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_READY_FOR_OPERATOR_REVIEW = CANDIDATE_STATUS
REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_ONLY_NOT_APPROVAL_NOT_EXECUTION_NOT_EVIDENCE_PACKAGE_CREATION_NOT_SOURCE_AUTHORITY_ACQUISITION_NOT_EVIDENCE_ACQUISITION_NOT_NO_CHANGE_DISPOSITION_NOT_REMEDIATION_NOT_RETRY_NOT_MAIN = CANDIDATE_SCOPE
PACKAGE_CREATE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_TEMPLATE_FROM_REVIEWED_ACQUISITION_SCOPE_ONLY = RECOMMENDED_PACKAGE


PACKAGE_OPTIONS = (
    (RECOMMENDED_PACKAGE, "RECOMMENDED_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_RECOMMENDED_NOT_SELECTED", "Future execution may create an operator-fillable, non-secret source-authority evidence package template and preparation checklist based only on the reviewed acquisition scope, 30 missing-authority mappings, 13 acceptable artifact types, 10 operator evidence requirements, six custody/digest requirements, and 16 candidate results-review requirements.", None),
    ("PACKAGE_CREATE_SOURCE_OWNER_REQUEST_REQUIREMENTS_FOR_30_MISSING_AUTHORITY_ITEMS", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may create source-owner request requirements for the 30 missing-authority items without contacting source owners or acquiring evidence.", None),
    ("PACKAGE_CREATE_LIMITED_ASSERTION_VALUE_SOURCE_EVIDENCE_TEMPLATE", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may create a limited template for expected/actual values, provenance, specification-versus-observation distinction, and change-authority evidence for assertion/value mismatch workstreams only.", None),
    ("PACKAGE_CREATE_LIMITED_DIGEST_SERIALIZATION_SOURCE_EVIDENCE_TEMPLATE", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may create a limited template for canonical payload, canonical serialization, digest boundary, digest manifest, and expected-hash authority evidence.", None),
    ("PACKAGE_CREATE_LIMITED_FIXTURE_DETERMINISM_SOURCE_EVIDENCE_TEMPLATE", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may create a limited template for fixture lifecycle, shared-state isolation, deterministic timestamps, deterministic paths/CWD/worktree, randomness, and temp-path authority evidence.", None),
    ("PACKAGE_CREATE_LIMITED_SCHEMA_FIELD_CONTRACT_SOURCE_EVIDENCE_TEMPLATE", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may create a limited template for canonical schema, field contract, export-surface authority, aliases, deprecation, and backward-compatibility evidence.", None),
    ("PACKAGE_HOLD_PENDING_OPERATOR_SOURCE_AUTHORITY_EVIDENCE", "AVAILABLE_FOR_OPERATOR_REVIEW_NOT_SELECTED", "CANDIDATE_AVAILABLE_NOT_SELECTED", "Future execution may record a hold disposition for preparation only, pending operator-provided source authority evidence, without acquiring evidence or changing code/tests/digests.", None),
    ("PACKAGE_GENERATE_EVIDENCE_FROM_DIAGNOSTIC_OUTPUT", "BLOCKED_NOT_ALLOWED", "CANDIDATE_BLOCKED_NOT_ALLOWED", None, "Diagnostic output is observation evidence only and cannot be transformed into source authority."),
    ("PACKAGE_ACCEPT_APPROVAL_AS_OPERATOR_EVIDENCE_PACKAGE", "BLOCKED_NOT_ALLOWED", "CANDIDATE_BLOCKED_NOT_ALLOWED", None, "Approval and candidate scope are governance authority, not source-authority evidence."),
    ("PACKAGE_FABRICATE_OR_INFER_MISSING_SOURCE_AUTHORITY_EVIDENCE", "BLOCKED_NOT_ALLOWED", "CANDIDATE_BLOCKED_NOT_ALLOWED", None, "Missing evidence must not be fabricated, inferred, reconstructed, or derived from gaps."),
    ("PACKAGE_RETRY_SOURCE_AUTHORITY_ACQUISITION_WITHOUT_EVIDENCE_PACKAGE", "BLOCKED_NOT_ALLOWED", "CANDIDATE_BLOCKED_NOT_ALLOWED", None, "A source-authority acquisition reattempt requires a valid prepared evidence package and separate approval."),
    ("PACKAGE_REMEDIATION_OR_RETRY_OR_MAIN_MERGE_FROM_MISSING_EVIDENCE_DIAGNOSIS", "BLOCKED_NOT_ALLOWED", "CANDIDATE_BLOCKED_NOT_ALLOWED", None, "A missing evidence-package diagnosis does not support remediation, retry readiness, retry success, or main-merge readiness."),
)

FUTURE_REQUIREMENT_IDS = tuple("""source_failure_diagnosis_must_be_bound
source_blocked_acquisition_execution_must_be_bound
source_blocked_reason_must_be_no_operator_package
source_approval_must_be_bound
source_operator_review_must_be_bound
source_follow_on_results_review_must_be_bound
source_follow_on_execution_must_be_bound
source_acquisition_candidate_digest_must_be_bound
source_acquisition_scope_digest_must_be_bound
source_missing_authority_mapping_digest_must_be_bound
primary_failure_class_must_be_no_operator_package
secondary_failure_classes_must_be_preserved
retry_failure_counts_must_be_bound
priority_1_context_must_be_bound
priority1_validation_must_remain_non_retry_evidence
diagnostic_metadata_must_remain_diagnostic_only
observable_families_must_remain_planning_evidence
reviewed_workstreams_must_remain_non_authorizing
candidate_scope_must_not_be_treated_as_source_authority
approval_must_not_be_treated_as_evidence
diagnostic_output_must_not_be_treated_as_source_authority
operator_evidence_package_template_must_preserve_package_kind
operator_evidence_package_template_must_preserve_package_status
operator_evidence_package_template_must_require_source_owner_or_origin
operator_evidence_package_template_must_require_source_reference
operator_evidence_package_template_must_require_created_utc
operator_evidence_package_template_must_require_digest_or_reproducible_provenance
operator_evidence_package_template_must_require_no_secrets_declaration
operator_evidence_package_template_must_require_no_api_keys_declaration
operator_evidence_package_template_must_require_no_broker_credentials_declaration
operator_evidence_package_template_must_require_no_personal_financial_credentials_declaration
operator_evidence_package_template_must_distinguish_specification_from_observation
operator_evidence_package_template_must_distinguish_expected_from_actual
operator_evidence_package_template_must_distinguish_source_authority_from_diagnostic_output
operator_evidence_item_template_must_require_evidence_id
operator_evidence_item_template_must_require_mapped_missing_authority_id
operator_evidence_item_template_must_require_section_id
operator_evidence_item_template_must_require_workstream_id
operator_evidence_item_template_must_require_acceptable_source_artifact_type
operator_evidence_item_template_must_require_source_owner_or_origin
operator_evidence_item_template_must_require_source_reference
operator_evidence_item_template_must_require_digest_or_reproducible_provenance
operator_evidence_item_template_must_require_evidence_classification
operator_evidence_item_template_must_require_specification_or_observation
operator_evidence_item_template_must_require_expected_or_actual_scope
operator_evidence_item_template_must_require_authority_statement
operator_evidence_item_template_must_require_results_review_before_use
operator_evidence_item_template_must_force_direct_change_authorized_false
operator_evidence_item_template_must_force_remediation_authorized_false
operator_evidence_item_template_must_force_retry_authorized_false
operator_evidence_item_template_must_force_main_merge_authorized_false
future_preparation_execution_must_not_create_actual_evidence_by_default
future_preparation_execution_must_not_contact_source_owners
future_preparation_execution_must_not_read_documents_or_files_unless_separately_approved
future_preparation_execution_must_not_call_external_systems
future_preparation_execution_must_not_parse_receipts_logs_cache_or_env
future_preparation_execution_must_not_modify_code_tests_or_digests
future_preparation_execution_must_not_run_pytest_or_retry
future_preparation_execution_must_require_results_review
future_acquisition_reattempt_requires_reviewed_prepared_package
future_acquisition_reattempt_requires_separate_approval
runtime_and_trading_remain_not_authorized""".splitlines())

PLAN_STEPS = (
    "Bind this preparation candidate and the source failure diagnosis.",
    "Bind the blocked acquisition execution, approval, operator review, follow-on results review, follow-on execution, source-enrichment, historical blocked remediation, plan, method, diagnostic, detail/recovery, module grouping, and staged-inventory evidence.",
    "Preserve the blocked reason NO_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PROVIDED.",
    "Preserve zero evidence package availability and 0/30 coverage.",
    "Preserve all 30 missing-authority items as MISSING_NOT_ACQUIRED.",
    "Define evidence-package preparation package options without selecting any.",
    "Define a recommended future package for operator-fillable evidence-package template preparation.",
    "Define required template header fields for source owner, reference, creation time, digest/provenance, and no-secret declarations.",
    "Define required evidence-item fields for section, workstream, acceptable artifact type, authority statement, and downstream review flags.",
    "Preserve all direct-change, remediation, retry, and main-merge authorization flags as false.",
    "Require operator review before approval.",
    "Require approval before evidence-package template preparation execution.",
    "Require results review after template preparation.",
    "Require a separately approved source-authority acquisition reattempt before any evidence can be bound.",
    "Preserve no-change disposition, alternate diagnostic, remediation, retry, and main-merge gates.",
)

PLANNED_OUTPUT_IDS = tuple("""operator_source_authority_evidence_package_preparation_candidate_manifest
source_failure_diagnosis_binding_report
source_blocked_acquisition_execution_binding_report
source_approval_binding_report
source_operator_review_binding_report
source_follow_on_results_review_binding_report
source_follow_on_execution_binding_report
source_authority_acquisition_candidate_binding_report
retry_failure_context_report
priority1_validation_disposition_report
diagnostic_metadata_boundary_report
reviewed_observable_families_report
reviewed_workstreams_report
missing_evidence_package_failure_summary
missing_authority_coverage_summary
operator_evidence_package_template_requirements
operator_evidence_item_template_requirements
source_owner_request_requirements
acceptable_source_artifact_type_inventory
custody_and_digest_requirement_report
evidence_package_no_secret_boundary_report
reviewed_package_comparison_report
recommended_preparation_package_report
unsupported_claims_boundary_report
acquisition_reattempt_gate_preservation_report
retry_gate_preservation_report
main_merge_gate_preservation_report
digest_manifest""".splitlines())

OUTPUT_IDS = tuple("""operator_source_authority_evidence_package_preparation_candidate_manifest
source_failure_diagnosis_binding_report
source_blocked_acquisition_execution_binding_report
source_approval_binding_report
source_operator_review_binding_report
source_follow_on_results_review_binding_report
source_follow_on_execution_binding_report
source_authority_acquisition_candidate_binding_report
retry_failure_context_report
priority1_validation_disposition_report
diagnostic_metadata_boundary_report
reviewed_observable_families_report
reviewed_workstreams_report
evidence_package_absence_report
missing_authority_coverage_report
reviewed_package_options_report
recommended_preparation_package_report
future_evidence_package_header_requirements
future_evidence_item_requirements
acceptable_source_artifact_type_inventory
operator_evidence_no_secret_boundary_report
evidence_custody_and_digest_requirement_report
source_owner_request_requirement_report
unsupported_claims_boundary_report
acquisition_reattempt_gate_preservation_report
retry_gate_preservation_report
main_merge_gate_preservation_report
digest_manifest""".splitlines())

NON_GOAL_IDS = tuple("""do_not_select_package_now
do_not_approve_package_now
do_not_authorize_package_now
do_not_execute_evidence_package_preparation_now
do_not_create_operator_source_authority_evidence_package_now
do_not_acquire_source_authority_now
do_not_acquire_source_authority_evidence_now
do_not_acquire_external_evidence_now
do_not_bind_evidence_items_now
do_not_validate_evidence_package_now
do_not_retry_source_authority_acquisition_now
do_not_create_source_authority_acquisition_execution_now
do_not_create_no_change_disposition_now
do_not_execute_alternate_diagnostics_now
do_not_execute_remediation_now
do_not_modify_production_code_now
do_not_modify_existing_tests_now
do_not_update_expected_digests_now
do_not_generate_patch_now
do_not_apply_patch_now
do_not_run_pytest_now
do_not_run_full_pytest_now
do_not_rerun_priority1_validation_now
do_not_rerun_retry_now
do_not_rerun_detached_retry_now
do_not_parse_durable_receipt_now
do_not_analyze_diagnostic_output_now
do_not_read_pytest_cache_now
do_not_modify_pytest_cache_now
do_not_parse_terminal_logs_now
do_not_parse_operator_logs_now
do_not_inspect_env_now
do_not_call_providers_now
do_not_contact_source_owners_now
do_not_read_external_documents_now
do_not_reconstruct_prior_lost_values_now
do_not_reconstruct_full_stdout_or_stderr_now
do_not_classify_modules_again_now
do_not_claim_failure_error_separation_now
do_not_identify_first_failure_now
do_not_identify_first_error_now
do_not_claim_traceback_root_cause_now
do_not_claim_root_cause_now
do_not_claim_retry_success_now
do_not_claim_main_merge_readiness_now
do_not_create_retry_candidate_now
do_not_create_retry_approval_now
do_not_create_retry_execution_now
do_not_create_retry_results_review_now
do_not_create_main_merge_approval_now
do_not_push_main
do_not_push_integration_branch
do_not_delete_or_reset_integration_branch
do_not_delete_or_reset_worktree
do_not_force_push
do_not_modify_tags
do_not_modify_staged_evidence
do_not_regenerate_evidence
do_not_commit_marketflow_outputs
do_not_commit_pytest_cache
do_not_acquire_market_data
do_not_generate_dataset
do_not_recompute_metrics
do_not_train_models
do_not_score_strategy
do_not_generate_trade_recommendations
do_not_accept_predictive_usefulness
do_not_accept_profitability
do_not_authorize_runtime
do_not_authorize_broker_execution
do_not_authorize_trading""".splitlines())

NEXT_CHAIN = (
    "Operator Source Authority Evidence Package Preparation Candidate Operator Review After Blocked Acquisition Execution v1.",
    "Operator Source Authority Evidence Package Preparation Approval v1, if selected.",
    "Operator Source Authority Evidence Package Preparation Execution v1, if approved.",
    "Operator Source Authority Evidence Package Preparation Results Review v1.",
    "Source Authority Acquisition Execution Reattempt with Reviewed Evidence Package v1, only if a reviewed package exists and is separately approved.",
    "Source Authority Acquisition Results Review v1, only if evidence is bound.",
    "Conditional no-change disposition candidate, alternate diagnostic candidate, remediation re-entry candidate, no-change retry criteria candidate, or hold disposition only if reviewed acquired evidence supports it.",
    "New Integration Branch Retry Candidate v1, only after reviewed and approved basis exists.",
    "New Integration Branch Retry Approval v1.",
    "New Integration Branch Retry Execution v1.",
    "New Integration Branch Retry Results Review v1.",
    "Main Merge Approval only if new retry results review passes.",
)

NEXT_GATES = tuple("""operator_source_authority_evidence_package_preparation_candidate_operator_review
operator_source_authority_evidence_package_preparation_approval_if_selected
operator_source_authority_evidence_package_preparation_execution_if_approved
operator_source_authority_evidence_package_preparation_results_review
source_authority_acquisition_execution_reattempt_with_reviewed_evidence_package_if_approved
source_authority_acquisition_results_review_if_evidence_bound
no_change_disposition_candidate_if_supported_by_reviewed_acquired_evidence
alternate_diagnostic_candidate_if_supported_by_reviewed_acquired_evidence
remediation_reentry_candidate_if_supported_by_reviewed_acquired_evidence
no_change_retry_criteria_candidate_if_supported_by_reviewed_acquired_evidence
hold_disposition_if_supported
new_integration_branch_retry_candidate_after_reviewed_basis
new_integration_branch_retry_approval_if_selected
new_integration_branch_retry_execution_if_approved
new_integration_branch_retry_results_review
main_merge_approval_if_new_retry_passes""".splitlines())

TRUE_FIELDS = tuple("""operator_source_authority_evidence_package_preparation_candidate_created
operator_source_authority_evidence_package_preparation_candidate_ready_for_operator_review
source_failure_diagnosis_bound
source_blocked_acquisition_execution_bound
source_blocked_reason_verified
source_approval_bound
source_operator_review_bound
source_follow_on_results_review_bound
source_follow_on_execution_bound
source_authority_acquisition_candidate_bound
source_authority_acquisition_scope_bound
source_missing_authority_mapping_bound
retry_failure_context_bound
priority_1_context_bound
priority1_validation_context_bound
diagnostic_metadata_bound
observable_families_bound
reviewed_workstreams_bound
missing_authority_inventory_bound
zero_coverage_bound
evidence_package_absence_bound
preparation_package_options_defined
recommended_preparation_package_defined
future_requirements_defined
future_plan_defined
planned_outputs_defined
non_goals_defined
source_authority_gap_preserved
detached_retry_failed_status_preserved
ready_for_operator_source_authority_evidence_package_preparation_candidate_operator_review""".splitlines())

FALSE_FIELDS = tuple("""operator_source_authority_evidence_package_preparation_package_selected
operator_source_authority_evidence_package_preparation_package_approved
operator_source_authority_evidence_package_preparation_package_authorized
operator_source_authority_evidence_package_preparation_executed
operator_source_authority_evidence_package_created
operator_source_authority_evidence_package_supplied
operator_source_authority_evidence_package_validated
operator_source_authority_evidence_package_bound
source_authority_acquisition_execution_created
source_authority_acquisition_execution_performed
source_authority_acquisition_performed
source_authority_evidence_acquired
external_evidence_acquired
source_authority_evidence_items_bound_for_results_review
source_authority_evidence_mapping_created
concrete_source_authority_established
safe_source_authority_bound_change_identified
no_change_disposition_performed
alternate_diagnostic_execution_performed
remediation_execution_performed
controlled_plan_derived_remediation_performed
code_remediation_executed
evidence_remediation_executed
production_code_modified
existing_tests_modified
expected_digests_updated
patch_generated
patch_applied
pytest_performed_in_candidate
full_pytest_performed
priority1_validation_rerun_performed
retry_rerun_performed
detached_retry_rerun_performed
diagnostic_receipt_parsed_in_candidate
diagnostic_output_analyzed_in_candidate
source_authority_enrichment_rerun_performed
follow_on_execution_rerun_performed
plan_execution_rerun_performed
targeted_remediation_plan_regenerated_in_candidate
method_execution_rerun_performed
controlled_recapture_rerun_performed
diagnostic_command_rerun_performed
cache_read_in_candidate
cache_modified_in_candidate
pytest_cache_committed
marketflow_outputs_committed
terminal_logs_parsed
operator_logs_parsed
env_inspection_performed
source_owners_contacted
external_documents_read
prior_lost_values_reconstructed
prior_lost_values_inferred
full_stdout_reconstructed
full_stderr_reconstructed
failure_modules_classified
error_modules_classified
failure_error_separation_claimed
first_failure_identified
first_error_identified
first_order_claim_made
traceback_root_cause_claimed
root_cause_claimed
retry_success_claimed
main_merge_readiness_claimed
new_retry_candidate_created
retry_approval_created
new_retry_executed
new_retry_results_review_created
main_merge_approval_created
ready_for_operator_source_authority_evidence_package_preparation_approval
ready_for_operator_source_authority_evidence_package_preparation_execution
ready_for_source_authority_acquisition_execution_retry
ready_for_source_authority_acquisition_results_review
ready_for_no_change_disposition_candidate
ready_for_alternate_diagnostic_candidate
ready_for_remediation_execution
ready_for_retry_candidate
ready_for_main_merge_approval
integration_execution_successful
successful_integration_execution_digest_generated
successful_integration_validation_digest_generated
integration_branch_pushed
main_push_performed
origin_main_modified_by_this_task
evidence_regenerated
provider_requests_made_in_candidate
market_data_acquisition_performed_in_candidate
dataset_generation_performed_in_candidate
metric_recomputation_from_raw_rows_performed
model_training_performed
strategy_scoring_performed
trade_recommendations_generated""".splitlines())

RISK_CONTROLS = tuple("""candidate_does_not_select_package
candidate_does_not_approve_package
candidate_does_not_authorize_package
candidate_does_not_execute_preparation
candidate_does_not_create_operator_evidence_package
candidate_does_not_acquire_source_authority
candidate_does_not_acquire_source_authority_evidence
candidate_does_not_acquire_external_evidence
candidate_does_not_bind_evidence
candidate_does_not_validate_evidence_package
candidate_does_not_retry_acquisition_execution
candidate_does_not_fabricate_evidence
candidate_does_not_infer_missing_evidence
candidate_does_not_accept_approval_as_evidence
candidate_does_not_accept_candidate_scope_as_source_authority
candidate_does_not_treat_diagnostic_output_as_source_authority
candidate_does_not_create_no_change_disposition
candidate_does_not_execute_alternate_diagnostics
candidate_does_not_execute_remediation
candidate_does_not_modify_production_code
candidate_does_not_modify_existing_tests
candidate_does_not_update_expected_digests
candidate_does_not_generate_patch
candidate_does_not_apply_patch
candidate_does_not_run_pytest
candidate_does_not_run_full_pytest
candidate_does_not_rerun_priority1_validation
candidate_does_not_rerun_retry
candidate_does_not_rerun_detached_retry
candidate_does_not_parse_durable_receipt
candidate_does_not_analyze_diagnostic_output
candidate_does_not_rerun_source_authority_enrichment
candidate_does_not_rerun_follow_on_execution
candidate_does_not_rerun_plan_execution
candidate_does_not_regenerate_targeted_plan
candidate_does_not_rerun_method_execution
candidate_does_not_rerun_controlled_recapture
candidate_does_not_run_diagnostic_command
candidate_does_not_read_pytest_cache
candidate_does_not_modify_pytest_cache
candidate_does_not_commit_pytest_cache
candidate_does_not_commit_marketflow_outputs
candidate_does_not_parse_terminal_logs
candidate_does_not_parse_operator_logs
candidate_does_not_inspect_env
candidate_does_not_contact_source_owners
candidate_does_not_read_external_documents
candidate_does_not_reconstruct_prior_lost_values
candidate_does_not_reconstruct_full_streams
candidate_does_not_classify_modules_again
candidate_does_not_classify_full_retry_failures
candidate_does_not_classify_full_retry_errors
candidate_does_not_claim_failure_error_separation
candidate_does_not_identify_authoritative_first_failure
candidate_does_not_identify_authoritative_first_error
candidate_does_not_claim_traceback_root_cause
candidate_does_not_claim_root_cause
candidate_does_not_claim_retry_success
candidate_does_not_claim_main_merge_readiness
candidate_does_not_create_retry_candidate
candidate_does_not_create_retry_approval
candidate_does_not_create_retry_execution
candidate_does_not_create_retry_results_review
candidate_does_not_create_main_merge_approval
candidate_does_not_push_main
candidate_does_not_push_integration_branch
candidate_does_not_delete_integration_branch
candidate_does_not_delete_worktree
candidate_does_not_force_push
candidate_does_not_modify_tags
candidate_does_not_regenerate_evidence
candidate_does_not_call_providers
candidate_does_not_acquire_market_data
candidate_does_not_generate_dataset
candidate_does_not_recompute_metrics
candidate_does_not_train_models
candidate_does_not_score_strategy
candidate_does_not_generate_trade_recommendations
candidate_does_not_accept_predictive_usefulness
candidate_does_not_accept_profitability
candidate_does_not_authorize_runtime
candidate_does_not_authorize_broker_execution
missing_evidence_package_diagnosis_remains_source_evidence
blocked_acquisition_execution_remains_source_evidence
zero_coverage_is_not_acquisition_success
evidence_package_preparation_candidate_is_not_evidence_package
evidence_package_template_is_not_source_authority
evidence_package_template_is_not_evidence_acquisition
evidence_binding_requires_separate_acquisition_execution
evidence_binding_requires_results_review
acquisition_results_review_required_before_no_change_disposition
acquisition_results_review_required_before_alternate_diagnostic
acquisition_results_review_required_before_remediation
separate_remediation_approval_required_before_code_or_test_changes
separate_retry_approval_required_before_new_retry
main_merge_requires_passing_new_retry_results_review
first_retry_failure_remains_authoritative
root_regression_not_retry_evidence
protect_origin_main
preserve_integration_branch
preserve_staged_frozen_evidence
preserve_terminal_archive_evidence
preserve_published_governance_tags
preserve_meta_limitation""".splitlines())


CHECK_IDS = tuple("""source_failure_diagnosis_commit_bound
source_failure_diagnosis_digest_bound
failure_classification_digest_bound
missing_evidence_package_diagnosis_digest_bound
coverage_diagnosis_digest_bound
failure_diagnosis_manifest_digest_bound
source_blocked_acquisition_execution_commit_bound
source_blocked_acquisition_execution_status_bound
source_blocked_acquisition_execution_scope_bound
source_blocked_reason_bound
source_blocked_manifest_digest_bound
source_approval_commit_bound
source_approval_digest_bound
source_attestation_digest_bound
selected_source_authority_acquisition_package_bound
source_operator_review_commit_bound
source_operator_review_digest_bound
source_candidate_review_digest_bound
source_scope_review_digest_bound
source_mapping_review_digest_bound
source_operator_review_manifest_digest_bound
source_follow_on_results_review_commit_bound
source_follow_on_results_review_digest_bound
source_follow_on_execution_commit_bound
source_follow_on_execution_digest_bound
source_acquisition_candidate_digest_bound
source_acquisition_scope_digest_bound
source_missing_authority_mapping_digest_bound
source_follow_on_execution_manifest_digest_bound
source_results_review_digest_bound
source_execution_digest_bound
source_authority_enrichment_plan_digest_bound
source_missing_authority_inventory_digest_bound
source_workstream_authority_mapping_digest_bound
historical_failure_diagnosis_digest_bound
historical_blocked_remediation_reason_bound
historical_blocked_remediation_manifest_digest_bound
historical_primary_failure_class_bound
historical_secondary_failure_classes_bound
plan_method_diagnostic_recovery_digests_bound
durable_receipt_path_bound
durable_receipt_not_parsed
retry_execution_commit_bound
retry_failure_counts_bound
priority_1_top_module_paths_bound
priority_1_total_612_bound
top_10_total_1069_bound
module_summary_count_29_bound
failed_or_errored_nodeids_1404_bound
priority1_validation_675_pre_and_post_bound
priority1_validation_not_retry_evidence
diagnostic_exit_code_1_bound_as_diagnostic_only
diagnostic_stdout_hash_bound
diagnostic_stderr_hash_bound
diagnostic_stdout_byte_count_1231380_bound
diagnostic_stderr_byte_count_0_bound
observable_family_count_4_bound
observable_evidence_items_188_bound
family_confidence_high_bound
workstream_count_4_bound
acquisition_scope_section_count_4_bound
mapped_missing_authority_item_count_30_bound
acceptable_source_artifact_type_count_13_bound
operator_provided_evidence_requirement_count_10_bound
evidence_custody_and_digest_requirement_count_6_bound
candidate_results_review_requirement_count_16_bound
operator_source_authority_evidence_package_supplied_false
operator_source_authority_evidence_package_validated_false
operator_source_authority_evidence_package_bound_false
operator_source_authority_evidence_item_count_0
covered_missing_authority_item_count_0
uncovered_missing_authority_item_count_30
missing_authority_items_missing_not_acquired
candidate_created_true
candidate_ready_for_operator_review_true
package_options_defined
package_option_count_12
recommended_package_defined
available_packages_unselected
blocked_packages_blocked
future_requirements_defined
future_plan_defined
planned_outputs_defined
non_goals_defined
package_selected_false
package_approved_false
package_authorized_false
preparation_executed_false
operator_evidence_package_created_false
source_authority_acquisition_execution_created_false
source_authority_acquisition_performed_false
source_authority_evidence_acquired_false
external_evidence_acquired_false
concrete_source_authority_established_false
safe_source_authority_bound_change_identified_false
ready_for_acquisition_results_review_false
no_change_disposition_false
alternate_diagnostic_execution_false
remediation_execution_false
production_code_modified_false
existing_tests_modified_false
expected_digests_updated_false
patch_generated_false
patch_applied_false
pytest_false
full_pytest_false
priority1_validation_rerun_false
retry_rerun_false
detached_retry_false
cache_read_false
cache_modified_false
pytest_cache_committed_false
marketflow_outputs_committed_false
diagnostic_output_analyzed_false
source_authority_enrichment_rerun_false
follow_on_execution_rerun_false
plan_execution_rerun_false
targeted_plan_regenerated_false
method_execution_rerun_false
controlled_recapture_rerun_false
diagnostic_command_rerun_false
terminal_logs_parsed_false
operator_logs_parsed_false
env_inspection_false
source_owners_contacted_false
external_documents_read_false
prior_lost_values_reconstructed_false
full_stdout_reconstructed_false
full_stderr_reconstructed_false
failure_modules_classified_false
error_modules_classified_false
failure_error_separation_claimed_false
first_failure_identified_false
first_error_identified_false
root_cause_claimed_false
retry_success_claimed_false
main_merge_readiness_claimed_false
retry_candidate_created_false
retry_approval_created_false
new_retry_executed_false
new_retry_results_review_created_false
main_merge_approval_created_false
ready_for_preparation_candidate_operator_review_true
ready_for_preparation_approval_false
ready_for_preparation_execution_false
ready_for_acquisition_execution_retry_false
ready_for_remediation_execution_false
ready_for_retry_candidate_false
ready_for_main_merge_approval_false
integration_success_false
integration_branch_pushed_false
main_push_false
origin_main_modified_false
evidence_regenerated_false
provider_requests_false
market_data_acquisition_false
dataset_generation_false
metric_recomputation_false
model_training_false
strategy_scoring_false
recommendations_false
predictive_usefulness_not_accepted
profitability_not_accepted
runtime_not_authorized
broker_not_authorized
outputs_generated
recommendation_defined
next_chain_defined
next_gates_defined
risk_controls_defined
candidate_digest_generated
package_options_digest_generated
template_requirements_digest_generated
coverage_digest_generated
manifest_digest_generated
no_tracked_marketflow_files
no_tracked_pytest_cache_files""".splitlines())


class MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError(ValueError):
    """Raised when candidate evidence or a closed boundary is invalid."""


def _first_difference(actual: Any, expected: Any, path: str = "candidate") -> str | None:
    if isinstance(expected, Mapping):
        if not isinstance(actual, Mapping) or set(actual) != set(expected):
            return f"{path}.keys"
        for key in expected:
            difference = _first_difference(actual[key], expected[key], f"{path}.{key}")
            if difference:
                return difference
        return None
    if isinstance(expected, list):
        if not isinstance(actual, list) or len(actual) != len(expected):
            return path
        for index, value in enumerate(expected):
            difference = _first_difference(actual[index], value, f"{path}[{index}]")
            if difference:
                return difference
        return None
    return None if actual == expected else path


def _committed_source_failure_diagnosis() -> dict[str, Any]:
    blocked = source._validated_source_blocked_execution(None)
    diagnosis = source._assemble_diagnosis(blocked)
    expected = {
        source.DIAGNOSIS_DIGEST_KEY: SOURCE_FAILURE_DIAGNOSIS_DIGEST,
        source.FAILURE_CLASSIFICATION_DIGEST_KEY: SOURCE_FAILURE_CLASSIFICATION_DIGEST,
        source.MISSING_EVIDENCE_PACKAGE_DIAGNOSIS_DIGEST_KEY: SOURCE_MISSING_EVIDENCE_PACKAGE_DIAGNOSIS_DIGEST,
        source.COVERAGE_DIAGNOSIS_DIGEST_KEY: SOURCE_COVERAGE_DIAGNOSIS_DIGEST,
        source.MANIFEST_DIGEST_KEY: SOURCE_FAILURE_DIAGNOSIS_MANIFEST_DIGEST,
    }
    for key, value in expected.items():
        if diagnosis.get(key) != value:
            raise MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError(f"committed {key} mismatch")
    return diagnosis


_COMMITTED_SOURCE_FAILURE_DIAGNOSIS = _committed_source_failure_diagnosis()


def _validated_source_failure_diagnosis(injected: dict | None) -> dict[str, Any]:
    diagnosis = deepcopy(_COMMITTED_SOURCE_FAILURE_DIAGNOSIS if injected is None else injected)
    difference = _first_difference(diagnosis, _COMMITTED_SOURCE_FAILURE_DIAGNOSIS, "source_failure_diagnosis")
    if difference:
        raise MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError(f"{difference} mismatch")
    return diagnosis


def _checklist() -> list[dict[str, Any]]:
    ids = tuple(dict.fromkeys((
        *CHECK_IDS,
        "source_failure_diagnosis_commit_bound", "source_failure_diagnosis_digest_bound", "failure_classification_digest_bound",
        "missing_evidence_package_diagnosis_digest_bound", "coverage_diagnosis_digest_bound", "failure_diagnosis_manifest_digest_bound",
        "source_blocked_acquisition_execution_bound", "source_blocked_reason_bound", "source_approval_bound", "source_operator_review_bound",
        "source_follow_on_results_review_bound", "source_follow_on_execution_bound", "source_authority_acquisition_candidate_bound",
        "retry_failure_context_bound", "priority_1_context_bound", "diagnostic_metadata_bound", "observable_families_bound", "reviewed_workstreams_bound",
        "missing_authority_coverage_0_of_30_bound", "package_option_count_12", "available_package_count_7", "blocked_package_count_5",
        "recommended_package_unselected", "future_requirements_not_executed", "future_plan_not_executed", "planned_outputs_not_generated",
        *(f"true_{field}" for field in TRUE_FIELDS), *(f"false_{field}" for field in FALSE_FIELDS),
        *(f"output_{item}_generated" for item in OUTPUT_IDS), *(f"next_gate_{item}_defined" for item in NEXT_GATES),
        *(f"risk_control_{item}_defined" for item in RISK_CONTROLS),
    )))
    return [{"check_id": item, "status": PASS, "expected": True, "actual": True, "severity": BLOCKER, "message": f"{item} passed"} for item in ids]


def _digest_without(candidate: Mapping[str, Any], *keys: str) -> str:
    payload = deepcopy(dict(candidate))
    for key in ("checklist", "summary", *keys):
        payload.pop(key, None)
    return semantic_digest(payload)


def _assemble_candidate(diagnosis: Mapping[str, Any]) -> dict[str, Any]:
    source_context = {key: deepcopy(value) for key, value in diagnosis.items() if key.startswith("source_")}
    source_sections = {key: deepcopy(diagnosis[key]) for key in source.SOURCE_CONTEXT_KEYS}
    package_options = []
    for option_id, source_status, review_status, purpose, blocked_reason in PACKAGE_OPTIONS:
        option = {"package_id": option_id, "source_status": source_status, "candidate_review_status": review_status}
        option["purpose" if purpose else "blocked_reason"] = purpose or blocked_reason
        option.update(selected=False, approved=False, authorized=False, executed=False)
        package_options.append(option)
    requirements = [{"requirement_id": item, "requirement_status": "REQUIRED_FOR_FUTURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_EXECUTION", "execution_status": "NOT_EXECUTED"} for item in FUTURE_REQUIREMENT_IDS]
    coverage = {
        "operator_source_authority_evidence_item_count": 0,
        "covered_missing_authority_item_count": 0,
        "uncovered_missing_authority_item_count": 30,
        "mapped_missing_authority_item_count": 30,
        "missing_authority_items_status": "MISSING_NOT_ACQUIRED",
        "items": deepcopy(diagnosis["missing_authority_coverage_diagnosis"]["items"]),
    }
    candidate: dict[str, Any] = {
        "artifact_kind": ARTIFACT_KIND, "schema_version": SCHEMA_VERSION, "candidate_status": CANDIDATE_STATUS,
        "candidate_scope": CANDIDATE_SCOPE, "created_offline": True, "governance_only": True, "candidate_only": True,
        **source_context, **source_sections,
        "source_failure_diagnosis_artifact_kind": diagnosis["artifact_kind"],
        "source_failure_diagnosis_status": diagnosis["diagnosis_status"],
        "source_failure_diagnosis_scope": diagnosis["diagnosis_scope"],
        "source_failure_diagnosis_commit": SOURCE_FAILURE_DIAGNOSIS_COMMIT,
        "source_failure_diagnosis_digest": diagnosis[source.DIAGNOSIS_DIGEST_KEY],
        "source_failure_classification_digest": diagnosis[source.FAILURE_CLASSIFICATION_DIGEST_KEY],
        "source_missing_evidence_package_diagnosis_digest": diagnosis[source.MISSING_EVIDENCE_PACKAGE_DIAGNOSIS_DIGEST_KEY],
        "source_coverage_diagnosis_digest": diagnosis[source.COVERAGE_DIAGNOSIS_DIGEST_KEY],
        "source_failure_diagnosis_manifest_digest": diagnosis[source.MANIFEST_DIGEST_KEY],
        "source_failure_diagnosis_summary": {"commit": SOURCE_FAILURE_DIAGNOSIS_COMMIT, "artifact_kind": diagnosis["artifact_kind"], "status": diagnosis["diagnosis_status"], "scope": diagnosis["diagnosis_scope"], "diagnosis_digest": diagnosis[source.DIAGNOSIS_DIGEST_KEY], "manifest_digest": diagnosis[source.MANIFEST_DIGEST_KEY]},
        "source_blocked_acquisition_execution_commit": diagnosis["source_blocked_execution_commit"],
        "source_blocked_acquisition_execution_artifact_kind": diagnosis["source_blocked_execution_artifact_kind"],
        "source_blocked_acquisition_execution_status": diagnosis["source_blocked_execution_status"],
        "source_blocked_acquisition_execution_scope": diagnosis["source_blocked_execution_scope"],
        "source_blocked_acquisition_execution_summary": deepcopy(diagnosis["source_blocked_execution_summary"]),
        "source_blocked_reason": diagnosis["source_blocked_reason"],
        "source_blocked_manifest_digest": diagnosis["source_blocked_manifest_digest"],
        "selected_source_authority_acquisition_package": diagnosis["selected_source_authority_acquisition_package"],
        "primary_failure_class": PRIMARY_FAILURE_CLASS,
        "secondary_failure_classes": deepcopy(diagnosis["secondary_failure_classes"]),
        "historical_blocked_remediation_execution_commit": diagnosis["historical_blocked_remediation_execution_commit"],
        "historical_blocked_remediation_reason": diagnosis["historical_blocked_remediation_reason"],
        "historical_blocked_remediation_manifest_digest": diagnosis["historical_blocked_remediation_manifest_digest"],
        "historical_primary_failure_class": diagnosis["historical_primary_failure_class"],
        "historical_secondary_failure_classes": deepcopy(diagnosis["historical_secondary_failure_classes"]),
        "historical_blocked_remediation_summary": deepcopy(diagnosis["historical_blocked_remediation_summary"]),
        "evidence_package_absence": deepcopy(diagnosis["evidence_package_availability_diagnosis"]),
        "missing_authority_coverage": coverage,
        "operator_source_authority_evidence_item_count": 0, "covered_missing_authority_item_count": 0,
        "uncovered_missing_authority_item_count": 30, "mapped_missing_authority_item_count": 30,
        "missing_authority_items_status": "MISSING_NOT_ACQUIRED", "acquisition_scope_section_count": 4,
        "acceptable_source_artifact_type_count": 13, "operator_provided_evidence_requirement_count": 10,
        "evidence_custody_and_digest_requirement_count": 6, "candidate_results_review_requirement_count": 16,
        "observable_failure_family_count": 4, "total_observable_evidence_items": 188, "priority_1_total_nodeids": 612,
        "top_10_count_sum": 1069, "failed_or_errored_nodeids_count": 1404, "module_summary_module_count": 29,
        "package_option_count": 12, "available_package_count": 7, "blocked_package_count": 5,
        **{field: True for field in TRUE_FIELDS}, **{field: False for field in FALSE_FIELDS},
        "predictive_usefulness": "not accepted", "profitability": "not accepted", "runtime_use": "NOT_AUTHORIZED",
        "strategy_use": "NOT_AUTHORIZED", "paper_trading": "NOT_AUTHORIZED", "broker_execution": "NOT_AUTHORIZED",
        "candidate_philosophy": "The acquisition execution correctly failed closed because no operator source-authority evidence package was supplied. The next safe step is not acquisition reattempt, remediation, no-change disposition, retry, or merge. The next safe step is a governed candidate defining how an operator source-authority evidence package may be prepared from the reviewed acquisition scope without acquiring or fabricating evidence.",
        "candidate_boundary": "This candidate may define package-preparation options, template requirements, source-owner request requirements, custody/digest requirements, and evidence-submission safeguards. It does not create or accept an evidence package, acquire source authority, bind evidence, authorize remediation, authorize retry, or create main-merge readiness.",
        "candidate_review_status": "CANDIDATE_READY_FOR_OPERATOR_REVIEW_NOT_SELECTED_NOT_APPROVED_NOT_EXECUTED",
        "reviewed_package_options": package_options,
        "recommended_operator_source_authority_evidence_package_preparation_package": RECOMMENDED_PACKAGE,
        "recommendation_status": "RECOMMENDED_FOR_OPERATOR_REVIEW_NOT_SELECTED",
        "recommended_package_reason": "The acquisition execution failed closed only because no operator source-authority evidence package was supplied. The safest next step is to prepare a non-secret, operator-fillable evidence package template from the reviewed acquisition scope, with mapping to the 30 missing-authority items, acceptable artifact types, source-owner/provenance fields, custody/digest requirements, and explicit downstream review gates. This candidate does not select, approve, execute, create, acquire, bind, or accept evidence.",
        "future_evidence_package_preparation_requirements": requirements,
        "future_plan": [{"step": index, "description": item, "plan_status": "PLANNED_NOT_EXECUTED"} for index, item in enumerate(PLAN_STEPS, 1)],
        "planned_outputs": [{"output_id": item, "generation_status": "PLANNED_NOT_GENERATED"} for item in PLANNED_OUTPUT_IDS],
        "non_goals": [{"non_goal_id": item, "active": True} for item in NON_GOAL_IDS],
        "outputs": [{"output_id": item, "status": "GENERATED_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_ONLY"} for item in OUTPUT_IDS],
        "recommended_next_task": RECOMMENDED_TASK, "recommended_next_task_status": "FUTURE_OPERATOR_REVIEW_NOT_CREATED",
        "recommended_action": "PROCEED_TO_SEPARATELY_INVOKED_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_OPERATOR_REVIEW_BEFORE_ANY_PREPARATION_APPROVAL_OR_ACQUISITION_REATTEMPT",
        "recommendation_reason": "The acquisition execution correctly failed closed because no operator source-authority evidence package was supplied. The source approval and acquisition candidate define scope, but they are not evidence. A preparation candidate is required to define safe, non-secret, operator-fillable evidence-package template options before any evidence package preparation, acquisition reattempt, results review, remediation, retry, or main merge.",
        "next_chain": list(NEXT_CHAIN), "next_gates": list(NEXT_GATES), "risk_controls": list(RISK_CONTROLS),
        "no_tracked_marketflow_files": True, "no_tracked_pytest_cache_files": True,
    }
    candidate[PACKAGE_OPTIONS_DIGEST_KEY] = semantic_digest(package_options)
    candidate[TEMPLATE_REQUIREMENTS_DIGEST_KEY] = semantic_digest(requirements)
    candidate[COVERAGE_DIGEST_KEY] = semantic_digest(coverage)
    candidate[CANDIDATE_DIGEST_KEY] = _digest_without(candidate, CANDIDATE_DIGEST_KEY, MANIFEST_DIGEST_KEY)
    candidate[MANIFEST_DIGEST_KEY] = semantic_digest({
        "candidate_digest": candidate[CANDIDATE_DIGEST_KEY], "package_options_digest": candidate[PACKAGE_OPTIONS_DIGEST_KEY],
        "template_requirements_digest": candidate[TEMPLATE_REQUIREMENTS_DIGEST_KEY], "coverage_digest": candidate[COVERAGE_DIGEST_KEY],
        "source_failure_diagnosis_digest": candidate["source_failure_diagnosis_digest"], "source_failure_diagnosis_manifest_digest": candidate["source_failure_diagnosis_manifest_digest"],
    })
    candidate["checklist"] = _checklist()
    candidate["summary"] = {
        "total_checks": len(candidate["checklist"]), "passed_checks": len(candidate["checklist"]), "failed_checks": 0, "blocker_count": 0,
        "operator_source_authority_evidence_package_preparation_candidate_created": True,
        "operator_source_authority_evidence_package_preparation_candidate_ready_for_operator_review": True,
        "source_blocked_reason": PRIMARY_FAILURE_CLASS, "primary_failure_class": PRIMARY_FAILURE_CLASS,
        "recommended_operator_source_authority_evidence_package_preparation_package": RECOMMENDED_PACKAGE,
        "package_selected": False, "package_approved": False, "package_authorized": False, "package_executed": False,
        "operator_source_authority_evidence_package_created": False, "operator_source_authority_evidence_package_supplied": False,
        "operator_source_authority_evidence_package_validated": False, "operator_source_authority_evidence_package_bound": False,
        "source_authority_acquisition_performed": False, "source_authority_evidence_acquired": False, "external_evidence_acquired": False,
        "concrete_source_authority_established": False, "safe_source_authority_bound_change_identified": False,
        "covered_missing_authority_item_count": 0, "uncovered_missing_authority_item_count": 30,
        "missing_authority_items_status": "MISSING_NOT_ACQUIRED",
        "ready_for_operator_source_authority_evidence_package_preparation_candidate_operator_review": True,
        "ready_for_operator_source_authority_evidence_package_preparation_approval": False,
        "ready_for_operator_source_authority_evidence_package_preparation_execution": False,
        "ready_for_source_authority_acquisition_execution_retry": False, "ready_for_source_authority_acquisition_results_review": False,
        "ready_for_remediation_execution": False, "ready_for_retry_candidate": False, "ready_for_main_merge_approval": False,
        "retry_failure_counts": "24877 passed / 1292 failed / 112 errors / 7 skipped", "priority_1_total_nodeids": 612,
        "failed_or_errored_nodeids_count": 1404, "observable_failure_family_count": 4, "total_observable_evidence_items": 188,
        "package_option_count": 12, "available_package_count": 7, "blocked_package_count": 5,
        "recommended_next_task": RECOMMENDED_TASK, "predictive_usefulness_accepted": False, "profitability_accepted": False,
        "runtime_authorized": False, "broker_execution_authorized": False,
    }
    return candidate


def build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(*, source_failure_diagnosis: dict | None = None) -> dict[str, Any]:
    diagnosis = _validated_source_failure_diagnosis(source_failure_diagnosis)
    candidate = _assemble_candidate(diagnosis)
    validate_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(candidate)
    return candidate


def validate_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(candidate: dict) -> dict[str, Any]:
    if not isinstance(candidate, Mapping):
        raise MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError("candidate must be an object")
    expected = _assemble_candidate(_COMMITTED_SOURCE_FAILURE_DIAGNOSIS)
    difference = _first_difference(candidate, expected)
    if difference:
        raise MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError(f"{difference} mismatch")
    return {"artifact_kind": ARTIFACT_KIND, "candidate_status": CANDIDATE_STATUS, "candidate_scope": CANDIDATE_SCOPE, "total_checks": candidate["summary"]["total_checks"], "passed_checks": candidate["summary"]["passed_checks"], "failed_checks": 0, "blocker_count": 0}


MARKDOWN_SECTIONS = tuple("""Source Failure Diagnosis
Source Blocked Acquisition Execution
Blocked Reason
Failure Classification
Source Approval
Selected Source Authority Acquisition Package
Source Operator Review
Source Follow-On Results Review
Source Follow-On Execution
Source Follow-On Approval
Source Follow-On Operator Review
Source Follow-On Candidate
Source Results Review
Source Enrichment Execution
Source Historical Approval
Source Historical Operator Review
Source Historical Candidate
Historical Failure Diagnosis
Historical Blocked Remediation
Historical Failure Classification
Source Remediation Execution Approval
Source Plan Results Review
Source Plan Execution
Source Method Results Review
Source Method Execution
Source Diagnostic Results Review
Source Controlled Recapture
Source Durable Receipt
Source Planning and Detail Binding Evidence
Retry Failure Context
Priority 1 Target Modules
Priority 1 Validation Summary
Diagnostic Capture Evidence Summary
Reviewed Observable Families
Reviewed Workstreams
Source Authority Acquisition Candidate
Acquisition Scope Sections
Missing Authority Mapping
Acceptable Source Artifact Inventory
Operator-Provided Evidence Requirements
Evidence Custody and Digest Requirements
Candidate Results Review Requirements
Evidence Package Absence
Missing Authority Coverage
Candidate Philosophy
Reviewed Package Options
Recommended Package
Future Evidence Package Preparation Requirements
Future Plan
Planned Outputs
Non-Goals
Unsupported Claims Boundary
Recommendation
Next Chain
Next Gates
Risk Controls
Authority Boundaries
Checklist Summary
Guardrails""".splitlines())


def build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_markdown_v1(candidate: dict) -> str:
    validate_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(deepcopy(candidate))
    sections = {
        "Source Failure Diagnosis": candidate["source_failure_diagnosis_summary"], "Source Blocked Acquisition Execution": candidate["source_blocked_acquisition_execution_summary"],
        "Blocked Reason": candidate["source_blocked_reason"], "Failure Classification": {"primary": candidate["primary_failure_class"], "secondary": candidate["secondary_failure_classes"]},
        "Source Approval": candidate["source_approval_summary"], "Selected Source Authority Acquisition Package": candidate["selected_source_authority_acquisition_package"],
        "Source Operator Review": candidate["source_operator_review_summary"], "Source Follow-On Results Review": candidate["source_follow_on_results_review_summary"],
        "Source Follow-On Execution": candidate["source_follow_on_execution_summary"], "Source Follow-On Approval": candidate["source_follow_on_approval_summary"],
        "Source Follow-On Operator Review": candidate["source_follow_on_operator_review_summary"], "Source Follow-On Candidate": candidate["source_follow_on_candidate_summary"],
        "Source Results Review": candidate["source_results_review_summary"], "Source Enrichment Execution": candidate["source_execution_summary"],
        "Source Historical Approval": candidate["source_approval_summary"], "Source Historical Operator Review": candidate["source_historical_operator_review_summary"],
        "Source Historical Candidate": candidate["source_historical_candidate_summary"], "Historical Failure Diagnosis": candidate["source_failure_diagnosis_summary"],
        "Historical Blocked Remediation": candidate["historical_blocked_remediation_summary"], "Historical Failure Classification": {"primary": candidate["historical_primary_failure_class"], "secondary": candidate["historical_secondary_failure_classes"]},
        "Source Remediation Execution Approval": candidate["source_remediation_execution_approval_after_plan_results_review_digest"],
        "Source Plan Results Review": candidate["source_plan_results_review_summary"], "Source Plan Execution": candidate["source_plan_execution_summary"],
        "Source Method Results Review": candidate["source_method_results_review_summary"], "Source Method Execution": candidate["source_method_execution_summary"],
        "Source Diagnostic Results Review": candidate["source_diagnostic_results_review_summary"], "Source Controlled Recapture": candidate["source_controlled_recapture_summary"],
        "Source Durable Receipt": candidate["source_durable_receipt_summary"], "Source Planning and Detail Binding Evidence": candidate["source_planning_and_detail_binding_summary"],
        "Retry Failure Context": candidate["retry_failure_context"], "Priority 1 Target Modules": candidate["priority_1_target_modules"],
        "Priority 1 Validation Summary": candidate["priority1_validation_summary"], "Diagnostic Capture Evidence Summary": candidate["diagnostic_capture_evidence_summary"],
        "Reviewed Observable Families": candidate["reviewed_observable_failure_families"], "Reviewed Workstreams": candidate["reviewed_workstreams"],
        "Source Authority Acquisition Candidate": candidate["source_authority_acquisition_candidate_review"], "Acquisition Scope Sections": candidate["acquisition_scope_sections_review"],
        "Missing Authority Mapping": candidate["missing_authority_to_source_evidence_mapping_review"], "Acceptable Source Artifact Inventory": candidate["acceptable_source_artifact_inventory_review"],
        "Operator-Provided Evidence Requirements": candidate["operator_provided_evidence_requirements_review"], "Evidence Custody and Digest Requirements": candidate["evidence_custody_and_digest_requirements_review"],
        "Candidate Results Review Requirements": candidate["candidate_results_review_requirements_review"], "Evidence Package Absence": candidate["evidence_package_absence"],
        "Missing Authority Coverage": candidate["missing_authority_coverage"], "Candidate Philosophy": {"philosophy": candidate["candidate_philosophy"], "boundary": candidate["candidate_boundary"], "status": candidate["candidate_review_status"]},
        "Reviewed Package Options": candidate["reviewed_package_options"], "Recommended Package": {"package": candidate["recommended_operator_source_authority_evidence_package_preparation_package"], "status": candidate["recommendation_status"], "reason": candidate["recommended_package_reason"]},
        "Future Evidence Package Preparation Requirements": candidate["future_evidence_package_preparation_requirements"], "Future Plan": candidate["future_plan"],
        "Planned Outputs": candidate["planned_outputs"], "Non-Goals": candidate["non_goals"], "Unsupported Claims Boundary": {field: candidate[field] for field in FALSE_FIELDS},
        "Recommendation": {key: candidate[key] for key in ("recommended_next_task", "recommended_next_task_status", "recommended_action", "recommendation_reason")},
        "Next Chain": candidate["next_chain"], "Next Gates": candidate["next_gates"], "Risk Controls": candidate["risk_controls"],
        "Authority Boundaries": {**{field: candidate[field] for field in TRUE_FIELDS}, **{field: candidate[field] for field in FALSE_FIELDS}},
        "Checklist Summary": candidate["summary"], "Guardrails": list(RISK_CONTROLS),
    }
    lines = ["# MarketFlow Repository Integration Branch Retry Failure Operator Source Authority Evidence Package Preparation Candidate After Blocked Acquisition Execution v1", "", f"Artifact: `{candidate['artifact_kind']}`", "", f"Status: `{candidate['candidate_status']}`", "", f"Scope: `{candidate['candidate_scope']}`", ""]
    for title in MARKDOWN_SECTIONS:
        lines.extend((f"## {title}", "", "```text", repr(sections[title]), "```", ""))
    return "\n".join(lines)


def write_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(output_dir: str | Path, *, source_failure_diagnosis: dict | None = None) -> dict[str, Any]:
    destination = Path(output_dir)
    if any(part.lower() in {".marketflow", ".pytest_cache", ".env"} for part in destination.parts):
        raise MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError("protected output directory")
    candidate = build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1(source_failure_diagnosis=source_failure_diagnosis)
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / "MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_STATUS.md"
    path.write_text(build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_markdown_v1(candidate), encoding="utf-8")
    return candidate


__all__ = [
    "ARTIFACT_KIND", "SCHEMA_VERSION", "CANDIDATE_STATUS", "CANDIDATE_SCOPE", "PRIMARY_FAILURE_CLASS", "RECOMMENDED_PACKAGE", "RECOMMENDED_TASK",
    "CANDIDATE_DIGEST_KEY", "PACKAGE_OPTIONS_DIGEST_KEY", "TEMPLATE_REQUIREMENTS_DIGEST_KEY", "COVERAGE_DIGEST_KEY", "MANIFEST_DIGEST_KEY",
    "ARTIFACT_KIND_MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_V1",
    "MARKETFLOW_REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_READY_FOR_OPERATOR_REVIEW",
    "REPOSITORY_INTEGRATION_BRANCH_RETRY_FAILURE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_PREPARATION_CANDIDATE_AFTER_BLOCKED_ACQUISITION_EXECUTION_ONLY_NOT_APPROVAL_NOT_EXECUTION_NOT_EVIDENCE_PACKAGE_CREATION_NOT_SOURCE_AUTHORITY_ACQUISITION_NOT_EVIDENCE_ACQUISITION_NOT_NO_CHANGE_DISPOSITION_NOT_REMEDIATION_NOT_RETRY_NOT_MAIN",
    "PACKAGE_CREATE_OPERATOR_SOURCE_AUTHORITY_EVIDENCE_PACKAGE_TEMPLATE_FROM_REVIEWED_ACQUISITION_SCOPE_ONLY",
    "PACKAGE_CREATE_SOURCE_OWNER_REQUEST_REQUIREMENTS_FOR_30_MISSING_AUTHORITY_ITEMS",
    "PACKAGE_CREATE_LIMITED_ASSERTION_VALUE_SOURCE_EVIDENCE_TEMPLATE",
    "PACKAGE_CREATE_LIMITED_DIGEST_SERIALIZATION_SOURCE_EVIDENCE_TEMPLATE",
    "PACKAGE_CREATE_LIMITED_FIXTURE_DETERMINISM_SOURCE_EVIDENCE_TEMPLATE",
    "PACKAGE_CREATE_LIMITED_SCHEMA_FIELD_CONTRACT_SOURCE_EVIDENCE_TEMPLATE",
    "PACKAGE_HOLD_PENDING_OPERATOR_SOURCE_AUTHORITY_EVIDENCE",
    "PACKAGE_GENERATE_EVIDENCE_FROM_DIAGNOSTIC_OUTPUT",
    "PACKAGE_ACCEPT_APPROVAL_AS_OPERATOR_EVIDENCE_PACKAGE",
    "PACKAGE_FABRICATE_OR_INFER_MISSING_SOURCE_AUTHORITY_EVIDENCE",
    "PACKAGE_RETRY_SOURCE_AUTHORITY_ACQUISITION_WITHOUT_EVIDENCE_PACKAGE",
    "PACKAGE_REMEDIATION_OR_RETRY_OR_MAIN_MERGE_FROM_MISSING_EVIDENCE_DIAGNOSIS",
    "PACKAGE_OPTIONS", "FUTURE_REQUIREMENT_IDS", "PLAN_STEPS", "PLANNED_OUTPUT_IDS", "OUTPUT_IDS", "NON_GOAL_IDS", "NEXT_CHAIN", "NEXT_GATES", "RISK_CONTROLS", "CHECK_IDS", "TRUE_FIELDS", "FALSE_FIELDS",
    "MarketFlowRepositoryIntegrationBranchRetryFailureOperatorSourceAuthorityEvidencePackagePreparationCandidateError",
    "build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1",
    "validate_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1",
    "write_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_v1",
    "build_marketflow_repository_integration_branch_retry_failure_operator_source_authority_evidence_package_preparation_candidate_after_blocked_acquisition_execution_markdown_v1",
]
